// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/aa073574a3c547dba7544d80ff318d73ebfa7c65/pg-types/pg-types.d.ts
declare module "pg-types" {

    interface TypeParser {
        (value: any): any;
    }

    export function getTypeParser(oid: number, format: string): TypeParser;

    export function setTypeParser(oid: number, format: string, parseFn: TypeParser): void;
    export function setTypeParser(oid: number, parseFn: TypeParser): void;

    export namespace arrayParser {

        export function create(source: any, transform: TypeParser): { parse: () => any[] };

    }

}
